# CanonSim Workbench — strings.gd, the single translation boundary (ux-1).
#
# FRONTEND_UIUX_LAW §17: ONE boundary — `_tr()` keys over every user-facing
# GDScript string; localization-READY layout (Cyrillic-safe metrics,
# wrapping, long-label tolerance), never hard-coded literals in surface
# code. The catalogs carry the EN values the shell previously inlined
# (the migration is literal-exact: the EN entry IS the old literal) and
# the RU companion (the owner's language; resolved by OS locale, the
# --lang user arg, or the CANONSIM_LANG env — see shell.gd _resolve_locale).
#
# The NOT-localized set (kept literal in shell.gd by law):
#   · protocol/contract values — model lifecycle states (DISCOVERED /
#     ACTIVE / SELECTED / EVICTED / LOADING / UNLOADING / FAILED), the
#     fa forms (on/off/auto), wire names (chat.send, run.get, …) — the
#     canonical vocabulary is displayed verbatim, never re-worded
#   · the authority vocabulary line (CANONICAL · OBSERVED · DERIVED ·
#     UNKNOWN · HIDDEN · VISUAL) — terms, not prose
#   · byte-size formats (GB/MB/B) — locale-neutral units
#
# Proof mode pins locale "en" (the byte-identical capture law, §22).
extends RefCounted

const EN := {
        "app.title": "CanonSim Workbench",
        "app.badge.not_connected": "CANONSIM · NOT CONNECTED",
        "app.badge.gateway_live": "CANONSIM · GATEWAY LIVE",
        "app.badge.session_live": "CANONSIM · SESSION LIVE",
        "nav.surfaces": "SURFACES",
        "nav.planned": "PLANNED · LATER WB ROWS",
        "nav.version": "%s · theme %s",
        "nav.chat": "Chat",
        "nav.models": "Models",
        "nav.settings": "Settings",
        "nav.planned.prompts": "Prompts",
        "nav.planned.history": "History",
        "nav.planned.diagnostics": "Diagnostics",
        "nav.planned.simulation": "Simulation",
        "chat.title": "Chat",
        "chat.subtitle": "The live circuit: the gateway's chat.send observed to its truthful terminal (wb-7).",
        "chat.empty.title": "No messages",
        "chat.empty.note": "Nothing is fabricated: the backend is not connected.",
        "chat.empty.note_live": "Session live over the gateway — nothing fabricated, ever.",
        "chat.empty.unreachable": "Gateway unreachable — start Workbench.bat (one double-click) or scripts/workbench_launch.py (%s).",
        "chat.busy.label": "GENERATING — the model is answering (Stop cancels)",
        "chat.composer.offline": "Offline — start Workbench.bat (one double-click), then reopen",
        "chat.composer.placeholder": "Message… (Enter to send)",
        "chat.send": "Send",
        "chat.stop": "Stop",
        "chat.stop.tooltip": "Stop the active generation (Esc or Ctrl+.)",
        "chat.role.user": "USER",
        "chat.role.assistant": "ASSISTANT",
        "chat.note.trimmed": "display trimmed to the last %d messages (bounded, §15)",
        "chat.note.dispatched": "chat dispatched (run %s · polling run.get)",
        "chat.note.outcome_unknown": "chat dispatch OUTCOME UNKNOWN (%s) — not blindly retried",
        "chat.note.app_refused": "app.status refused: %s %s",
        "chat.note.session_refused": "session.create refused: %s %s",
        "chat.note.run_cancel_refused": "run.cancel refused: %s %s",
        "chat.note.unexpected": "unexpected answer for %s (status %s)",
        "chat.note.get_refused": "run.get refused: %s %s",
        "chat.note.finish": "finish %s · backend %s",
        "chat.note.run_failed": "run FAILED · %s",
        "chat.note.run_canceled": "run canceled (the truthful terminal)",
        "chat.note.cancel_failed": "cancel failed — the late result was recorded and shown",
        "chat.note.run_unknown": "run OUTCOME UNKNOWN — the observation stands, no blind retry",
        "chat.note.run_unmodelled": "run terminal state %s (unmodelled — shown, never collapsed)",
        "chat.note.poll_abandoned": "poll abandoned after %d transport failures (%s)",
        "chat.note.cancel_transport": "run.cancel transport failure (%s) — the poll continues",
        "chat.note.transport": "transport failure on %s (%s)",
        "chat.backend.unavailable": "unavailable (no backend identity in the run result)",
        "chat.backend.probe_unavailable": "probe unavailable — the identity not observed (honest note)",
        "chat.backend.unknown_model": "unknown model",
        "chat.backend.unknown_build": "unknown build",
        "chat.backend.no_identity": "no backend identity in the run result (shown, never guessed)",
        "chat.backend.observed_probe": "llama.cpp chat OBSERVED · identity probe unavailable (honest)",
        "chat.backend.observed": "OBSERVED · %s",
        "models.title": "Models",
        "models.subtitle": "Discover, fetch, load, switch — the lifecycle states observed, never guessed (wb-8/wb-9).",
        "models.refresh": "Refresh",
        "models.active.none": "active: none observed",
        "models.active.observed": "active: %s",
        "models.add_files": "Add local models…",
        "models.add_files.tooltip": "Pick GGUF files anywhere on disk — the OS file dialog",
        "models.add_folder": "Add folder…",
        "models.add_folder.tooltip": "Pick a folder — every .gguf inside lands as a model",
        "models.open_folder": "Open models folder",
        "models.open_folder.tooltip": "The models directory in the OS file manager",
        "common.cancel": "Cancel",
        "models.import_cancel.tooltip": "Cancel the running import (the truthful §12.3 terminal)",
        "models.manager.offline": "the manager rides the gateway — start Workbench.bat (double-click) or scripts/workbench_launch.py",
        "models.needs_live": "the models manager needs a live gateway session — the badge (top right) names the state; start Workbench.bat",
        "models.one_transfer": "one transfer at a time — wait for the current one to land (or cancel it)",
        "models.advanced": "Download by URL… (advanced)",
        "models.fetch.placeholder": "https://…/model.gguf · hf:repo/file — pull a GGUF from anywhere",
        "models.fetch": "Fetch",
        "models.empty.title": "No models discovered",
        "models.empty.note": "No models yet — click Add local models… and pick GGUF files from your disk (or Add folder…).",
        "models.status.idle": "model actions: none yet",
        "models.status.scanning": "scanning the models directory…",
        "models.status.list_refused": "model.list refused: %s %s",
        "models.status.states_refused": "model.states refused: %s %s",
        "models.status.missing_dir": "The models directory is MISSING — the launcher's runtime/models folder is the default home; fetch or drop GGUF files there.",
        "models.status.none_found": "no models discovered (%s) — Add local models… above, or drop GGUF files into %s",
        "models.status.discovered": "%d model(s) discovered · %s",
        "models.action.load": "Load",
        "models.action.unload": "Unload",
        "models.action.loading": "LOADING…",
        "models.action.unloading": "UNLOADING…",
        "models.status.load_needs_live": "the load action needs a live gateway session — the badge (top right) names the state; start Workbench.bat",
        "models.status.unload_needs_live": "the unload action needs a live gateway session — the badge (top right) names the state; start Workbench.bat",
        "models.status.loading": "loading %s — dispatched as a run (the spawn/readiness walk rides the poll; the app stays live)",
        "models.status.unloading": "unloading %s — dispatched as a run (the graceful stop rides the poll)",
        "models.status.load_unknown": "model.load dispatch OUTCOME UNKNOWN (%s) — the state is NOT changed; Load may be re-issued deliberately",
        "models.status.unload_unknown": "model.unload dispatch OUTCOME UNKNOWN (%s) — the state is NOT changed; Unload may be re-issued deliberately",
        "models.status.load_refused": "model.load refused: %s %s",
        "models.status.unload_refused": "model.unload refused: %s %s",
        "models.status.loading_walk": "loading %s — the run is %s (the managed spawn is minutes-class, observed live)",
        "models.status.unloading_walk": "unloading %s — the run is %s",
        "models.status.active_ready": "%s ACTIVE — the chat surface is ready",
        "models.status.load_failed": "load FAILED · %s — %s",
        "models.status.load_canceled": "load canceled (the truthful terminal)",
        "models.status.load_unmodelled": "load terminal state %s (unmodelled — shown, never collapsed)",
        "models.status.evicted": "%s EVICTED — Load again to re-select",
        "models.status.unload_failed": "unload FAILED · %s — %s (the observed truth stays ACTIVE)",
        "models.status.unload_canceled": "unload canceled (the truthful terminal)",
        "models.status.unload_unmodelled": "unload terminal state %s (unmodelled — shown, never collapsed)",
        "models.status.load_abandoned": "load poll abandoned after %d transport failures (%s) — the row rests at its observed truth",
        "models.status.unload_abandoned": "unload poll abandoned after %d transport failures (%s) — the row rests at its observed truth",
        "models.status.action_transport": "%s transport failure (%s) — the state is NOT changed, the action may be re-issued",
        "models.status.unreachable": "gateway unreachable on %s (%s) — Retry with Refresh",
        "models.dialog.gguf": "*.gguf ; GGUF model files",
        "models.dialog.all": "* ; All files",
        "fetch.status.url_first": "paste a URL first — a direct link, a huggingface.co page, or hf:repo/file",
        "fetch.status.dispatching": "dispatching the fetch run…",
        "fetch.status.fetching": "fetching — the progress rides the run poll",
        "fetch.status.outcome_unknown": "fetch dispatch OUTCOME UNKNOWN (%s) — not blindly retried",
        "fetch.status.refused": "model.fetch refused: %s %s",
        "fetch.status.fetched": "fetched %s (%s) — refreshing the list",
        "fetch.status.failed": "fetch FAILED · %s",
        "fetch.status.canceled": "fetch canceled (the truthful terminal)",
        "fetch.status.unmodelled": "fetch terminal state %s (unmodelled — shown, never collapsed)",
        "fetch.status.folder_pending": "the models folder path arrives with the first models scan — Refresh",
        "fetch.status.open_failed": "the OS file manager refused to open %s (error %d)",
        "fetch.status.no_gguf": "no .gguf files in %s — pick the folder that holds them",
        "fetch.status.importing_count": "importing %d file(s)…",
        "fetch.status.importing": "importing — the progress rides the run poll",
        "fetch.status.import_unknown": "import dispatch OUTCOME UNKNOWN (%s) — not blindly retried",
        "fetch.status.import_refused": "model.import refused: %s %s",
        "fetch.status.imported": "imported %d model(s) — refreshing the list",
        "fetch.status.import_failed": "import FAILED · %s",
        "fetch.status.import_canceled": "import canceled (the truthful terminal)",
        "fetch.status.import_unmodelled": "import terminal state %s (unmodelled — shown, never collapsed)",
        "fetch.status.dispatch_transport": "fetch dispatch transport failure (%s) — nothing sent, safe to retry",
        "fetch.status.import_dispatch_transport": "import dispatch transport failure (%s) — nothing sent, safe to retry",
        "fetch.status.import_abandoned": "import poll abandoned after %d transport failures (%s)",
        "fetch.status.fetch_abandoned": "fetch poll abandoned after %d transport failures (%s)",
        "fetch.progress.unknown_total": "downloading %s — %s (total unknown)",
        "fetch.progress.percent": "downloading %s — %d%% (%s / %s)",
        "fetch.progress.plain": "downloading %s — %s",
        "fetch.progress.no_diagnostics": "no diagnostics",
        "import.progress.percent": "importing %s (%d/%d) — %d%% (%s / %s)",
        "import.progress.plain": "importing %s (%d/%d) — %s",
        "settings.title": "Settings",
        "settings.subtitle": "Global behaviour and appearance — the effective values, honestly.",
        "settings.theme": "Theme",
        "settings.theme.value": "canon_workbench_theme@0.4 · dark — the only admitted theme",
        "settings.language": "Language",
        "settings.language.value": "English · Russian (OS locale, --lang, CANONSIM_LANG) — the _tr boundary (ux-1)",
        "settings.gateway": "Gateway",
        "settings.gateway.offline": "offline — the proof/static form (no gateway dialled)",
        "settings.gateway.probing": "offline — probing %s",
        "settings.gateway.live": "LIVE · %s",
        "settings.gateway.unreachable": "unreachable · %s",
        "settings.backend": "Backend",
        "settings.backend.none": "none observed yet — llama.cpp rides the gateway (chat.run's backend note)",
        "settings.simulation": "Simulation",
        "settings.simulation.value": "seam proven (wb-1) · the surface opens on its wb row",
        "settings.keyboard": "Keyboard & focus",
        "settings.keyboard.value": "Esc stops a generation · Ctrl+. stops from anywhere · task-aware focus per surface (ux-1)",
        "settings.interface": "Interface",
        "settings.reduced_motion": "Reduce motion — static equivalents for every tween/pulse",
        "settings.launch.title": "llama.cpp launch (managed)",
        "settings.launch.note": "The managed spawn's own flags — saved values apply at the NEXT model.load; a LIVE server keeps its flags until unloaded.",
        "settings.launch.exe": "llama-server executable",
        "settings.launch.exe.placeholder": "auto — workbench/runtime/llama.cpp, then PATH",
        "settings.launch.ctx": "Context window (-c)",
        "settings.launch.ngl": "GPU layers (-ngl)",
        "settings.launch.fa": "Flash attention (-fa)",
        "settings.launch.jinja": "Chat template (--jinja)",
        "settings.launch.no_webui": "No web UI (--no-webui)",
        "settings.launch.sampler": "SAMPLER DEFAULTS",
        "settings.launch.temp": "Temperature (--temp)",
        "settings.launch.topk": "Top-K (--top-k)",
        "settings.launch.topp": "Top-P (--top-p)",
        "settings.launch.minp": "Min-P (--min-p)",
        "settings.launch.repeat": "Repeat penalty (--repeat-penalty)",
        "settings.launch.advanced": "Advanced — extra flags and the command preview",
        "settings.launch.extra": "Extra flags",
        "settings.launch.extra.placeholder": "--threads 8 --mlock — extra llama-server flags, verbatim",
        "settings.launch.preview": "the command the NEXT managed spawn would run — arrives with the gateway's settings document",
        "settings.status.offline": "the settings ride the gateway — start scripts/workbench_launch.py",
        "settings.status.saving": "saving…",
        "settings.status.effective": "effective values shown%s",
        "settings.status.effective_next": " — effective at the next model.load",
        "settings.status.effective_live": " — a LIVE server keeps its flags until unloaded",
        "settings.status.saved": "saved — the values apply at the next model.load (a LIVE server keeps its flags until unloaded)",
        "settings.status.save_unknown": "settings save OUTCOME UNKNOWN (%s) — not blindly retried",
        "settings.status.save_refused": "backend.settings.update refused: %s %s",
        "settings.status.settings_refused": "backend.settings refused: %s %s",
        "settings.status.unreachable": "backend.settings unreachable (%s) — the values stay local until the gateway answers",
        "settings.status.save_transport": "settings save transport failure (%s) — nothing sent, safe to retry",
        "settings.save": "Save launch settings",
        "status.legend": "Statuses CANONICAL · OBSERVED · DERIVED · UNKNOWN · HIDDEN · VISUAL are displayed, never collapsed",
        "status.gateway.offline": "gateway OFFLINE",
        "status.gateway.live": "gateway LIVE · %s",
        "status.gateway.unreachable": "gateway unreachable (%s)",
        "status.seam": "seam wb-1 · PROVEN",
        "status.engine": "Redot 26.2 LTS",
        "nav.group.work": "WORK",
        "nav.group.resources": "RESOURCES",
        "nav.group.system": "SYSTEM",
        "nav.observatory": "Observatory",
        "nav.inference": "Inference",
        "nav.planned.runs": "Runs",
        "inference.title": "Inference",
        "inference.subtitle": "The semantic generation-control workspace: chips are semantic runtime controls, not CLI flags — the resolver answers the effective state, the compiled command is technical detail.",
        "inference.refresh": "Refresh",
        "inference.save": "Save profile",
        "inference.advanced": "Compiled command (technical)",
        "inference.compiled.caption": "The command the NEXT spawn will run — the compiled artifact, never the authoring language.",
        "inference.context.offline": "profile: — (no read yet)",
        "inference.context.profile": "profile: %s",
        "inference.context.applies_next": "applies at the NEXT model.load spawn — a live server keeps its flags until unloaded",
        "inference.context.applies_live": "a LIVE server keeps its spawn flags until unloaded — the saved values apply at the next model.load",
        "inference.category.model": "Model / Runtime",
        "inference.category.device": "Device / GPU",
        "inference.category.memory": "Memory / KV",
        "inference.category.loading": "Model Loading",
        "inference.category.moe": "MoE",
        "inference.category.cpu": "CPU / NUMA",
        "inference.category.sampling": "Sampling",
        "inference.category.chat": "Chat / Reasoning",
        "inference.category.structured": "Structured Output",
        "inference.category.server": "Server / Concurrency",
        "inference.category.observability": "Observability",
        "inference.category.speculative": "Speculative Decoding",
        "inference.category.rope": "RoPE / YaRN",
        "inference.category.special": "Special Modes",
        "inference.category.lora": "LoRA",
        "inference.category.count": "%d controls",
        "inference.category.toggle.tooltip": "Open or collapse the category",
        "inference.search.placeholder": "Search controls (name, flag, category)...",
        "inference.search.advanced": "Advanced",
        "inference.text.placeholder": "(not set)",
        "inference.pin.tooltip": "Pin the control to the quick-access strip",
        "inference.pinned.caption": "Pinned (quick access)",
        "inference.pinned.empty": "No pinned controls — pin with the star on any row",
        "inference.pinned.chip.tooltip": "Jump to the control",
        "inference.preset.caption": "Preset:",
        "inference.preset.none": "(none)",
        "inference.preset.preview": "Preview",
        "inference.preset.apply": "Apply",
        "inference.preset.diff": "preset changes: %s",
        "inference.preset.diff.empty": "the preset matches the current profile — nothing would change",
        "inference.chain.title": "Sampler chain (ordered)",
        "inference.chain.note": "The order changes the emitted configuration — the chain is a first-class object, never a favorites grid. Disabled members stay configured, out of the emitted chain.",
        "inference.chain.enabled.tooltip": "Chain membership: disabled members keep their values but leave the emitted chain",
        "inference.chain.up": "up",
        "inference.chain.down": "down",
        "inference.status.offline": "offline — no read yet",
        "inference.status.probing": "probing the gateway...",
        "inference.status.resolved": "resolved — the states above are the server's own answer",
        "inference.status.refused": "inference.read refused: %s",
        "inference.status.transport": "transport failed: %s",
        "chat.inference.projection": "profile %s · temp %s",
        "chat.inference.link": "Inference...",
        "settings.launch.inference.link": "Semantic inference controls live in the Inference workspace...",
        "obs.title": "Observatory",
        "obs.subtitle": "The analytical instrument: question → scope → one primary view → inspector → evidence (obs-1 — read-only slice, the grammar before the backend coverage).",
        "obs.breadcrumb.root": "Observatory",
        "obs.breadcrumb.hint": "semantic path — the root; each step opens on its own row",
        "obs.context.pack": "pack",
        "obs.context.run": "run",
        "obs.context.seed": "seed",
        "obs.context.tick": "tick window",
        "obs.context.profile": "profile",
        "obs.context.revision": "revision",
        "obs.context.no_session": "— no session",
        "obs.context.empty_axis": "—",
        "obs.context.tick_range": "%d–%d",
        "obs.context.revision_format": "n=%d",
        "obs.question.title": "World Question",
        "obs.question.question": "QUESTION",
        "obs.question.class": "CLASS",
        "obs.question.target": "TARGET",
        "obs.question.scope": "SCOPE",
        "obs.question.not_set": "— not set —",
        "obs.lifecycle.draft": "DRAFT — nothing asked, nothing claimed",
        "obs.primary.title": "Primary view — events",
        "obs.column.tick": "TICK",
        "obs.column.event": "EVENT",
        "obs.column.kind": "KIND",
        "obs.column.authority": "AUTHORITY",
        "obs.empty.no_data": "NO DATA",
        "obs.empty.no_data_note": "No run is loaded: there is no world projection to observe yet (NOT “no match”, NOT “no evidence” — no data source exists).",
        "obs.inspector.title": "Inspector",
        "obs.inspector.nothing_selected": "Nothing is selected — selection opens here (identity · state · relations · provenance) when the primary view holds rows.",
        "obs.state.probing": "reading the runs root…",
        "obs.state.probing_note": "The listing has not answered yet — nothing is fabricated.",
        "obs.empty.no_runs": "NO RUNS",
        "obs.empty.no_runs_note": "The canonical runs root holds no runs yet — a simulation run (the cli) writes one; this is NO DATA, not “no match” and not “no evidence”.",
        "obs.empty.no_events": "NO EVENTS",
        "obs.empty.no_events_note": "This run holds only its header — zero events exist in it (not “no match”, not “no evidence”).",
        "obs.read.rejected": "READ REFUSED — %s",
        "obs.read.rejected_note": "The position resets to the head; Refresh re-reads. The refusal reason is the backend's own observed cause.",
        "obs.read.transport": "TRANSPORT FAILED — %s",
        "obs.runs.label": "Run",
        "obs.runs.refresh": "Refresh",
        "obs.runs.corrupt": "%s (unreadable)",
        "obs.page.earlier": "Earlier",
        "obs.page.later": "Later",
        "obs.page.status": "events %d–%d of %d",
        "obs.page.status_empty": "events 0 of 0",
        "obs.inspector.selected_title": "Inspector — %s",
        "obs.inspector.id": "identity",
        "obs.inspector.tick": "tick",
        "obs.inspector.type": "type",
        "obs.inspector.actor": "actor",
        "obs.inspector.kind": "outcome kind",
        "obs.inspector.importance": "importance",
        "obs.inspector.authority": "authority",
        "obs.inspector.cause": "declared cause",
        "obs.inspector.cause_none": "— none (a root event) —",
        "obs.inspector.state_changes": "state changes",
        "obs.inspector.state_change": "%s.%s: %s → %s",
        "obs.inspector.state_changes_none": "— none recorded —",
        "obs.inspector.knowledge": "knowledge records",
        "obs.inspector.provenance": "provenance",
        "obs.evidence.confirmed": "confirmed",
        "obs.evidence.scope_note": "scope: run %s · event %s",
        "obs.evidence.no_verified_claim": "no verified claim at this level",
        "obs.evidence.title": "Evidence ladder",
        "obs.evidence.read": "READ",
        "obs.evidence.branch": "BRANCH",
        "obs.evidence.state": "STATE",
        "obs.evidence.divergence": "DIVERGENCE",
        "obs.evidence.persistence": "PERSISTENCE",
        "obs.evidence.unknown": "?",
        "obs.evidence.no_claim": "no claim under inspection",
}

const RU := {
        "app.title": "CanonSim Workbench",
        "app.badge.not_connected": "CANONSIM · НЕТ СОЕДИНЕНИЯ",
        "app.badge.gateway_live": "CANONSIM · ШЛЮЗ АКТИВЕН",
        "app.badge.session_live": "CANONSIM · СЕССИЯ АКТИВНА",
        "nav.surfaces": "ПОВЕРХНОСТИ",
        "nav.planned": "ЗАПЛАНИРОВАНО · ПОЗДНЕЙШИЕ WB-СТРОКИ",
        "nav.version": "%s · тема %s",
        "nav.chat": "Чат",
        "nav.models": "Модели",
        "nav.settings": "Настройки",
        "nav.planned.prompts": "Промпты",
        "nav.planned.history": "История",
        "nav.planned.diagnostics": "Диагностика",
        "nav.planned.simulation": "Симуляция",
        "chat.title": "Чат",
        "chat.subtitle": "Живой контур: chat.send шлюза наблюдается до честного терминала (wb-7).",
        "chat.empty.title": "Сообщений нет",
        "chat.empty.note": "Ничего не выдумано: бэкенд не подключён.",
        "chat.empty.note_live": "Сессия жива через шлюз — ничего не выдумывается, никогда.",
        "chat.empty.unreachable": "Шлюз недоступен — запустите Workbench.bat (двойной клик) или scripts/workbench_launch.py (%s).",
        "chat.busy.label": "ГЕНЕРАЦИЯ — модель отвечает (Стоп отменяет)",
        "chat.composer.offline": "Автономно — запустите Workbench.bat (двойной клик) и откройте снова",
        "chat.composer.placeholder": "Сообщение… (Enter — отправить)",
        "chat.send": "Отправить",
        "chat.stop": "Стоп",
        "chat.stop.tooltip": "Остановить активную генерацию (Esc или Ctrl+.)",
        "chat.role.user": "ПОЛЬЗОВАТЕЛЬ",
        "chat.role.assistant": "ПОМОЩНИК",
        "chat.note.trimmed": "показ обрезан до последних %d сообщений (ограничено, §15)",
        "chat.note.dispatched": "чат отправлен (run %s · опрос run.get)",
        "chat.note.outcome_unknown": "результат отправки чата НЕИЗВЕСТЕН (%s) — без слепого повтора",
        "chat.note.app_refused": "app.status отклонён: %s %s",
        "chat.note.session_refused": "session.create отклонён: %s %s",
        "chat.note.run_cancel_refused": "run.cancel отклонён: %s %s",
        "chat.note.unexpected": "неожиданный ответ на %s (статус %s)",
        "chat.note.get_refused": "run.get отклонён: %s %s",
        "chat.note.finish": "завершение %s · бэкенд %s",
        "chat.note.run_failed": "run ПРОВАЛЕН · %s",
        "chat.note.run_canceled": "run отменён (честный терминал)",
        "chat.note.cancel_failed": "отмена не удалась — поздний результат записан и показан",
        "chat.note.run_unknown": "результат run НЕИЗВЕСТЕН — наблюдение сохраняется, без слепого повтора",
        "chat.note.run_unmodelled": "терминальное состояние run %s (не смоделировано — показано, не схлопнуто)",
        "chat.note.poll_abandoned": "опрос оставлен после %d транспортных сбоев (%s)",
        "chat.note.cancel_transport": "транспортный сбой run.cancel (%s) — опрос продолжается",
        "chat.note.transport": "транспортный сбой на %s (%s)",
        "chat.backend.unavailable": "недоступен (нет идентичности бэкенда в результате run)",
        "chat.backend.probe_unavailable": "проба недоступна — идентичность не наблюдается (честная пометка)",
        "chat.backend.unknown_model": "неизвестная модель",
        "chat.backend.unknown_build": "неизвестная сборка",
        "chat.backend.no_identity": "нет идентичности бэкенда в результате run (показано, не угадано)",
        "chat.backend.observed_probe": "чат llama.cpp НАБЛЮДАЕТСЯ · проба идентичности недоступна (честно)",
        "chat.backend.observed": "НАБЛЮДАЕТСЯ · %s",
        "models.title": "Модели",
        "models.subtitle": "Обнаружение, загрузка, смена — состояния жизненного цикла наблюдаемы, не угадываемы (wb-8/wb-9).",
        "models.refresh": "Обновить",
        "models.active.none": "активна: не наблюдалось",
        "models.active.observed": "активна: %s",
        "models.add_files": "Добавить локальные модели…",
        "models.add_files.tooltip": "Выберите GGUF-файлы где угодно на диске — системный диалог",
        "models.add_folder": "Добавить папку…",
        "models.add_folder.tooltip": "Выберите папку — каждый .gguf внутри станет моделью",
        "models.open_folder": "Открыть папку моделей",
        "models.open_folder.tooltip": "Каталог моделей в системном файловом менеджере",
        "common.cancel": "Отмена",
        "models.import_cancel.tooltip": "Отменить текущий импорт (честный терминал §12.3)",
        "models.manager.offline": "менеджер работает через шлюз — запустите Workbench.bat (двойной клик) или scripts/workbench_launch.py",
        "models.needs_live": "менеджеру моделей нужна живая сессия шлюза — бейдж (справа вверху) называет состояние; запустите Workbench.bat",
        "models.one_transfer": "одна передача за раз — дождитесь текущей (или отмените её)",
        "models.advanced": "Скачать по URL… (дополнительно)",
        "models.fetch.placeholder": "https://…/model.gguf · hf:repo/file — получить GGUF откуда угодно",
        "models.fetch": "Скачать",
        "models.empty.title": "Модели не обнаружены",
        "models.empty.note": "Моделей пока нет — нажмите «Добавить локальные модели…» и выберите GGUF-файлы на диске (или «Добавить папку…»).",
        "models.status.idle": "действия с моделями: пока нет",
        "models.status.scanning": "сканирование каталога моделей…",
        "models.status.list_refused": "model.list отклонён: %s %s",
        "models.status.states_refused": "model.states отклонён: %s %s",
        "models.status.missing_dir": "Каталог моделей ОТСУТСТВУЕТ — runtime/models лаунчера это дом по умолчанию; скачайте или положите GGUF туда.",
        "models.status.none_found": "модели не обнаружены (%s) — «Добавить локальные модели…» выше или положите GGUF в %s",
        "models.status.discovered": "обнаружено моделей: %d · %s",
        "models.action.load": "Загрузить",
        "models.action.unload": "Выгрузить",
        "models.action.loading": "ЗАГРУЗКА…",
        "models.action.unloading": "ВЫГРУЗКА…",
        "models.status.load_needs_live": "для загрузки нужна живая сессия шлюза — бейдж (справа вверху) называет состояние; запустите Workbench.bat",
        "models.status.unload_needs_live": "для выгрузки нужна живая сессия шлюза — бейдж (справа вверху) называет состояние; запустите Workbench.bat",
        "models.status.loading": "загрузка %s — отправлена как run (шаг спавна/готовности едет в опросе; приложение остаётся живым)",
        "models.status.unloading": "выгрузка %s — отправлена как run (мягкая остановка едет в опросе)",
        "models.status.load_unknown": "результат model.load НЕИЗВЕСТЕН (%s) — состояние НЕ изменено; «Загрузить» можно осознанно повторить",
        "models.status.unload_unknown": "результат model.unload НЕИЗВЕСТЕН (%s) — состояние НЕ изменено; «Выгрузить» можно осознанно повторить",
        "models.status.load_refused": "model.load отклонён: %s %s",
        "models.status.unload_refused": "model.unload отклонён: %s %s",
        "models.status.loading_walk": "загрузка %s — run %s (управляемый спавн минутного класса, наблюдается живьём)",
        "models.status.unloading_walk": "выгрузка %s — run %s",
        "models.status.active_ready": "%s АКТИВНА — поверхность чата готова",
        "models.status.load_failed": "загрузка ПРОВАЛЕНА · %s — %s",
        "models.status.load_canceled": "загрузка отменена (честный терминал)",
        "models.status.load_unmodelled": "терминальное состояние загрузки %s (не смоделировано — показано, не схлопнуто)",
        "models.status.evicted": "%s ВЫГРУЖЕНА — «Загрузить» снова для выбора",
        "models.status.unload_failed": "выгрузка ПРОВАЛЕНА · %s — %s (наблюдаемая истина остаётся АКТИВНОЙ)",
        "models.status.unload_canceled": "выгрузка отменена (честный терминал)",
        "models.status.unload_unmodelled": "терминальное состояние выгрузки %s (не смоделировано — показано, не схлопнуто)",
        "models.status.load_abandoned": "опрос загрузки оставлен после %d транспортных сбоев (%s) — строка покоится на наблюдаемой истине",
        "models.status.unload_abandoned": "опрос выгрузки оставлен после %d транспортных сбоев (%s) — строка покоится на наблюдаемой истине",
        "models.status.action_transport": "транспортный сбой %s (%s) — состояние НЕ изменено, действие можно повторить",
        "models.status.unreachable": "шлюз недоступен на %s (%s) — повторите через «Обновить»",
        "models.dialog.gguf": "*.gguf ; GGUF-файлы моделей",
        "models.dialog.all": "* ; Все файлы",
        "fetch.status.url_first": "сначала вставьте URL — прямая ссылка, страница huggingface.co или hf:repo/file",
        "fetch.status.dispatching": "отправка fetch-run…",
        "fetch.status.fetching": "скачивание — прогресс едет в опросе run",
        "fetch.status.outcome_unknown": "результат fetch НЕИЗВЕСТЕН (%s) — без слепого повтора",
        "fetch.status.refused": "model.fetch отклонён: %s %s",
        "fetch.status.fetched": "скачано %s (%s) — обновление списка",
        "fetch.status.failed": "fetch ПРОВАЛЕН · %s",
        "fetch.status.canceled": "fetch отменён (честный терминал)",
        "fetch.status.unmodelled": "терминальное состояние fetch %s (не смоделировано — показано, не схлопнуто)",
        "fetch.status.folder_pending": "путь к папке моделей придёт с первым сканированием — «Обновить»",
        "fetch.status.open_failed": "файловый менеджер отказался открывать %s (ошибка %d)",
        "fetch.status.no_gguf": "в %s нет .gguf — выберите папку, где они есть",
        "fetch.status.importing_count": "импорт файлов: %d…",
        "fetch.status.importing": "импорт — прогресс едет в опросе run",
        "fetch.status.import_unknown": "результат импорта НЕИЗВЕСТЕН (%s) — без слепого повтора",
        "fetch.status.import_refused": "model.import отклонён: %s %s",
        "fetch.status.imported": "импортировано моделей: %d — обновление списка",
        "fetch.status.import_failed": "импорт ПРОВАЛЕН · %s",
        "fetch.status.import_canceled": "импорт отменён (честный терминал)",
        "fetch.status.import_unmodelled": "терминальное состояние импорта %s (не смоделировано — показано, не схлопнуто)",
        "fetch.status.dispatch_transport": "транспортный сбой отправки fetch (%s) — ничего не отправлено, можно повторить",
        "fetch.status.import_dispatch_transport": "транспортный сбой отправки импорта (%s) — ничего не отправлено, можно повторить",
        "fetch.status.import_abandoned": "опрос импорта оставлен после %d транспортных сбоев (%s)",
        "fetch.status.fetch_abandoned": "опрос fetch оставлен после %d транспортных сбоев (%s)",
        "fetch.progress.unknown_total": "скачивание %s — %s (размер неизвестен)",
        "fetch.progress.percent": "скачивание %s — %d%% (%s / %s)",
        "fetch.progress.plain": "скачивание %s — %s",
        "fetch.progress.no_diagnostics": "диагностики нет",
        "import.progress.percent": "импорт %s (%d/%d) — %d%% (%s / %s)",
        "import.progress.plain": "импорт %s (%d/%d) — %s",
        "settings.title": "Настройки",
        "settings.subtitle": "Глобальное поведение и вид — действующие значения, честно.",
        "settings.theme": "Тема",
        "settings.theme.value": "canon_workbench_theme@0.4 · тёмная — единственная допущенная тема",
        "settings.language": "Язык",
        "settings.language.value": "English · Русский (локаль ОС, --lang, CANONSIM_LANG) — граница _tr (ux-1)",
        "settings.gateway": "Шлюз",
        "settings.gateway.offline": "автономно — статическая форма (шлюз не набирается)",
        "settings.gateway.probing": "автономно — проба %s",
        "settings.gateway.live": "АКТИВЕН · %s",
        "settings.gateway.unreachable": "недоступен · %s",
        "settings.backend": "Бэкенд",
        "settings.backend.none": "пока не наблюдался — llama.cpp за шлюзом (заметка бэкенда в chat.run)",
        "settings.simulation": "Симуляция",
        "settings.simulation.value": "шов доказан (wb-1) · поверхность откроется своей wb-строкой",
        "settings.keyboard": "Клавиатура и фокус",
        "settings.keyboard.value": "Esc останавливает генерацию · Ctrl+. останавливает отовсюду · осмысленный фокус при входе на поверхность (ux-1)",
        "settings.interface": "Интерфейс",
        "settings.reduced_motion": "Уменьшить анимацию — статические эквиваленты для каждого твина/пульса",
        "settings.launch.title": "Запуск llama.cpp (управляемый)",
        "settings.launch.note": "Флаги управляемого спавна — сохранённые значения применятся при СЛЕДУЮЩЕМ model.load; ЖИВОЙ сервер держит свои флаги до выгрузки.",
        "settings.launch.exe": "исполняемый файл llama-server",
        "settings.launch.exe.placeholder": "авто — workbench/runtime/llama.cpp, затем PATH",
        "settings.launch.ctx": "Окно контекста (-c)",
        "settings.launch.ngl": "Слои GPU (-ngl)",
        "settings.launch.fa": "Flash attention (-fa)",
        "settings.launch.jinja": "Шаблон чата (--jinja)",
        "settings.launch.no_webui": "Без web UI (--no-webui)",
        "settings.launch.sampler": "ДЕФОЛТЫ СЭМПЛЕРОВ",
        "settings.launch.temp": "Температура (--temp)",
        "settings.launch.topk": "Top-K (--top-k)",
        "settings.launch.topp": "Top-P (--top-p)",
        "settings.launch.minp": "Min-P (--min-p)",
        "settings.launch.repeat": "Штраф повтора (--repeat-penalty)",
        "settings.launch.advanced": "Дополнительно — дополнительные флаги и предпросмотр команды",
        "settings.launch.extra": "Дополнительные флаги",
        "settings.launch.extra.placeholder": "--threads 8 --mlock — дополнительные флаги llama-server, дословно",
        "settings.launch.preview": "команда, которую выполнит СЛЕДУЮЩИЙ управляемый спавн — приходит с документом настроек шлюза",
        "settings.status.offline": "настройки работают через шлюз — запустите scripts/workbench_launch.py",
        "settings.status.saving": "сохранение…",
        "settings.status.effective": "показаны действующие значения%s",
        "settings.status.effective_next": " — применятся при следующем model.load",
        "settings.status.effective_live": " — ЖИВОЙ сервер держит флаги до выгрузки",
        "settings.status.saved": "сохранено — значения применятся при следующем model.load (ЖИВОЙ сервер держит флаги до выгрузки)",
        "settings.status.save_unknown": "результат сохранения НЕИЗВЕСТЕН (%s) — без слепого повтора",
        "settings.status.save_refused": "backend.settings.update отклонён: %s %s",
        "settings.status.settings_refused": "backend.settings отклонён: %s %s",
        "settings.status.unreachable": "backend.settings недоступен (%s) — значения остаются локальными до ответа шлюза",
        "settings.status.save_transport": "транспортный сбой сохранения (%s) — ничего не отправлено, можно повторить",
        "settings.save": "Сохранить настройки запуска",
        "status.legend": "Статусы CANONICAL · OBSERVED · DERIVED · UNKNOWN · HIDDEN · VISUAL показываются, никогда не схлопываются",
        "status.gateway.offline": "шлюз ОФФЛАЙН",
        "status.gateway.live": "шлюз АКТИВЕН · %s",
        "status.gateway.unreachable": "шлюз недоступен (%s)",
        "status.seam": "шов wb-1 · ДОКАЗАН",
        "status.engine": "Redot 26.2 LTS",
        "nav.group.work": "РАБОТА",
        "nav.group.resources": "РЕСУРСЫ",
        "nav.group.system": "СИСТЕМА",
        "nav.observatory": "Обсерватория",
        "nav.inference": "Инференс",
        "nav.planned.runs": "Прогоны",
        "inference.title": "Инференс",
        "inference.subtitle": "Семантическое рабочее место управления генерацией: чип — семантический регулятор рантайма, не CLI-флаг; резолвер отвечает эффективное состояние, скомпилированная команда — техническая деталь.",
        "inference.refresh": "Обновить",
        "inference.save": "Сохранить профиль",
        "inference.advanced": "Скомпилированная команда (техническая)",
        "inference.compiled.caption": "Команда, которую запустит СЛЕДУЮЩИЙ спавн — скомпилированный артефакт, никогда не язык редактирования.",
        "inference.context.offline": "профиль: — (чтения ещё не было)",
        "inference.context.profile": "профиль: %s",
        "inference.context.applies_next": "применится при СЛЕДУЮЩЕМ model.load — живой сервер хранит свои флаги до выгрузки",
        "inference.context.applies_live": "ЖИВОЙ сервер хранит флаги спавна до выгрузки — сохранённые значения применятся при следующем model.load",
        "inference.category.model": "Модель / Рантайм",
        "inference.category.device": "Устройство / GPU",
        "inference.category.memory": "Память / KV",
        "inference.category.loading": "Загрузка модели",
        "inference.category.moe": "MoE",
        "inference.category.cpu": "CPU / NUMA",
        "inference.category.sampling": "Сэмплирование",
        "inference.category.chat": "Чат / Reasoning",
        "inference.category.structured": "Структурный вывод",
        "inference.category.server": "Сервер / Конкурентность",
        "inference.category.observability": "Наблюдаемость",
        "inference.category.speculative": "Спекулятивное декодирование",
        "inference.category.rope": "RoPE / YaRN",
        "inference.category.special": "Специальные режимы",
        "inference.category.lora": "LoRA",
        "inference.category.count": "регуляторов: %d",
        "inference.category.toggle.tooltip": "Открыть или свернуть категорию",
        "inference.search.placeholder": "Поиск регуляторов (имя, флаг, категория)...",
        "inference.search.advanced": "Расширенные",
        "inference.text.placeholder": "(не задано)",
        "inference.pin.tooltip": "Закрепить регулятор в полосе быстрого доступа",
        "inference.pinned.caption": "Закреплённые (быстрый доступ)",
        "inference.pinned.empty": "Нет закреплённых — закрепите звездой в любой строке",
        "inference.pinned.chip.tooltip": "Перейти к регулятору",
        "inference.preset.caption": "Пресет:",
        "inference.preset.none": "(нет)",
        "inference.preset.preview": "Показать",
        "inference.preset.apply": "Применить",
        "inference.preset.diff": "изменения пресета: %s",
        "inference.preset.diff.empty": "пресет совпадает с текущим профилем — изменений нет",
        "inference.chain.title": "Цепочка сэмплеров (упорядоченная)",
        "inference.chain.note": "Порядок меняет emitted-конфигурацию — цепочка это первоклассный объект, не сетка избранного. Отключённые члены остаются настроенными, вне выдаваемой цепочки.",
        "inference.chain.enabled.tooltip": "Членство в цепочке: отключённые члены хранят значения, но покидают выдаваемую цепочку",
        "inference.chain.up": "вверх",
        "inference.chain.down": "вниз",
        "inference.status.offline": "офлайн — чтения ещё не было",
        "inference.status.probing": "опрос шлюза...",
        "inference.status.resolved": "разрешено — состояния выше это ответ сервера",
        "inference.status.refused": "inference.read отклонён: %s",
        "inference.status.transport": "транспорт не удался: %s",
        "chat.inference.projection": "профиль %s · темп %s",
        "chat.inference.link": "Инференс...",
        "settings.launch.inference.link": "Семантические регуляторы инференса живут в рабочем месте «Инференс»...",
        "obs.title": "Обсерватория",
        "obs.subtitle": "Аналитический инструмент: вопрос → охват → один основной вид → инспектор → доказательства (obs-1 — доступный только для чтения срез, грамматика до бэкенда).",
        "obs.breadcrumb.root": "Обсерватория",
        "obs.breadcrumb.hint": "семантический путь — корень; каждый шаг откроется своей строкой",
        "obs.context.pack": "пак",
        "obs.context.run": "прогон",
        "obs.context.seed": "сид",
        "obs.context.tick": "окно тиков",
        "obs.context.profile": "профиль",
        "obs.context.revision": "ревизия",
        "obs.context.no_session": "— нет сессии",
        "obs.context.empty_axis": "—",
        "obs.context.tick_range": "%d–%d",
        "obs.context.revision_format": "n=%d",
        "obs.question.title": "Мировой вопрос",
        "obs.question.question": "ВОПРОС",
        "obs.question.class": "КЛАСС",
        "obs.question.target": "ЦЕЛЬ",
        "obs.question.scope": "ОХВАТ",
        "obs.question.not_set": "— не задан —",
        "obs.lifecycle.draft": "DRAFT — ничего не спрошено, ничего не утверждается",
        "obs.primary.title": "Основной вид — события",
        "obs.column.tick": "ТИК",
        "obs.column.event": "СОБЫТИЕ",
        "obs.column.kind": "ТИП",
        "obs.column.authority": "ПОЛНОМОЧИЕ",
        "obs.empty.no_data": "НЕТ ДАННЫХ",
        "obs.empty.no_data_note": "Ни один прогон не загружен: мировую проекцию пока не наблюдать (НЕ «нет совпадений», НЕ «нет доказательств» — источника данных не существует).",
        "obs.inspector.title": "Инспектор",
        "obs.inspector.nothing_selected": "Ничего не выбрано — выбор откроется здесь (идентичность · состояние · связи · происхождение), когда в основном виде появятся строки.",
        "obs.state.probing": "чтение каталога прогонов…",
        "obs.state.probing_note": "Ответ на запрос ещё не пришёл — ничего не сфабриковано.",
        "obs.empty.no_runs": "НЕТ ПРОГОНОВ",
        "obs.empty.no_runs_note": "В каноническом каталоге прогонов пока нет прогонов — прогон создаётся запуском симуляции (cli); это НЕТ ДАННЫХ, а не «нет совпадений» и не «нет доказательств».",
        "obs.empty.no_events": "НЕТ СОБЫТИЙ",
        "obs.empty.no_events_note": "Этот прогон содержит только заголовок — в нём ноль событий (не «нет совпадений» и не «нет доказательств»).",
        "obs.read.rejected": "ЧТЕНИЕ ОТКЛОНЕНО — %s",
        "obs.read.rejected_note": "Позиция сброшена к началу; «Обновить» перечитает. Причина отказа — наблюдённая причина самого бэкенда.",
        "obs.read.transport": "СБОЙ ТРАНСПОРТА — %s",
        "obs.runs.label": "Прогон",
        "obs.runs.refresh": "Обновить",
        "obs.runs.corrupt": "%s (нечитаем)",
        "obs.page.earlier": "Раньше",
        "obs.page.later": "Позже",
        "obs.page.status": "события %d–%d из %d",
        "obs.page.status_empty": "события 0 из 0",
        "obs.inspector.selected_title": "Инспектор — %s",
        "obs.inspector.id": "идентичность",
        "obs.inspector.tick": "тик",
        "obs.inspector.type": "тип",
        "obs.inspector.actor": "актор",
        "obs.inspector.kind": "вид исхода",
        "obs.inspector.importance": "важность",
        "obs.inspector.authority": "полномочие",
        "obs.inspector.cause": "заявленная причина",
        "obs.inspector.cause_none": "— нет (корневое событие) —",
        "obs.inspector.state_changes": "изменения состояния",
        "obs.inspector.state_change": "%s.%s: %s → %s",
        "obs.inspector.state_changes_none": "— не зафиксировано —",
        "obs.inspector.knowledge": "записи знания",
        "obs.inspector.provenance": "происхождение",
        "obs.evidence.confirmed": "подтверждено",
        "obs.evidence.scope_note": "охват: прогон %s · событие %s",
        "obs.evidence.no_verified_claim": "на этом уровне нет проверенного утверждения",
        "obs.evidence.title": "Лестница доказательств",
        "obs.evidence.read": "ЧТЕНИЕ",
        "obs.evidence.branch": "ВЕТВЛЕНИЕ",
        "obs.evidence.state": "СОСТОЯНИЕ",
        "obs.evidence.divergence": "РАСХОЖДЕНИЕ",
        "obs.evidence.persistence": "СТОЙКОСТЬ",
        "obs.evidence.unknown": "?",
        "obs.evidence.no_claim": "утверждение не исследуется",
}


static func lookup(key: String, locale: String) -> String:
        # The honest fallback: a missing key returns the key itself — visible
        # in review, never a silently wrong string (the boundary's own law).
        var catalog: Dictionary = RU if locale == "ru" else EN
        if catalog.has(key):
                return String(catalog[key])
        return key


static func locales() -> PackedStringArray:
        return PackedStringArray(["en", "ru"])
